version: '3.11'

services:
  app:
    build: .
    container_name: fastapi-docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "14.225.253.170", "--port", "8000"]