version: '3.11'

services:
  app:
    build: .
    container_name: fastapi-docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "script:app", "--host", "0.0.0.0", "--port", "8000"]